# importando o numpy

In [96]:
import numpy as np
print('Done.')

Done.

In [97]:
a = np.array(np.arange(10))
display(a)
display(a.ndim)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1

# Lista 2D

In [98]:
d = [
    [2, 3, 44]
] # array de 2D

d = np.array(d)
print(d)
print(d.ndim)

[[ 2  3 44]]
2

# Lista 3D

In [99]:
# array de 3D
d_3 = [
    [
        [3, 4, 11]
    ]
]

d3 = np.array(d_3)

print(d3)
print(f'{d3.ndim} dimen.')

[[[ 3  4 11]]]
3 dimen.

In [100]:
d_4 = [[[
    [3,11,23],[3,4,34]
]]]

res = np.array(d_4)
display(f'Essa lista é de dimenção {res.ndim}')
display(f'Tamnho {res.shape}')

'Essa lista é de dimenção 4'

'Tamnho (1, 1, 2, 3)'

# np.full() and np.ones()

In [101]:
display(np.full((2, 3), 1)) # cria uma matriz de 2x3 e nela exiba uma lista de matris de 1ns
display(np.ones((2, 3))) # cria uma matriz de 2x3 e nela exiba uma lista de matris de 1ns

array([[1, 1, 1],
       [1, 1, 1]])

array([[1., 1., 1.],
       [1., 1., 1.]])

# np.full() and np.zeros()

In [102]:
display(np.full((2, 3), 0))
display(np.zeros((2, 3)))

array([[0, 0, 0],
       [0, 0, 0]])

array([[0., 0., 0.],
       [0., 0., 0.]])

# np.random.seed() **and** np.random.randn()

In [103]:
np.random.seed(0)
a = np.random.randn(10)
print(a)
print(f'O valor maximo é: {a.max()}')
print(f'O valor minimo é: {a.min()}')

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
O valor maximo é: 2.240893199201458
O valor minimo é: -0.977277879876411

In [104]:
np.linspace(0, 10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Manipulation

In [105]:
list1 = np.arange(1,6)
list2 = np.arange(6, 11)

display(f'list1: {list1}')
display(f'list2: {list2}')

'list1: [1 2 3 4 5]'

'list2: [ 6  7  8  9 10]'

## np.hstack()

In [106]:
# serve para unir as listas no sentido horizontal
a = np.hstack((list1, list2))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
a_1 = np.ones((2, 4))
display(a_1)

a_2 = np.zeros((2,4))
display(a_2)


# unindo as duas listas de forma horizontal
np.hstack((a_1, a_2))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [108]:
a.shape

(10,)

# np.vstack()

In [109]:
# serve para unir duas listas no sentido vertical
a_1_2 = np.vstack((a_1, a_2))
a = np.vstack((list1, list2))

print("Array a_1_2: ")
display(a_1_2)

print("\nArray a: ")
display(a)

Array a_1_2:

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Array a:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# np.concatenate()

## np.concatenate() **vertical**

In [110]:
# Ela desempenha as duas funcoes do hstack() e do vstack().
# sintaxe: np.concatenate((A1, A2), axi = 0/1) axis = 1 para horizontal e axis = 0 para vertical
np.concatenate((a_1, a_2), axis = 0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.concatenate() **horizontal**

In [111]:
np.concatenate((a_1, a_2), axis= 1)

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

# np.reshape()

In [112]:
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]

In [113]:
array.reshape(2,5) # 2 linhas e 5 colunas

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [114]:
array.reshape(5,2) # quero 5 linhas e 2 colunas

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# np.squeeze()

In [115]:
#obs: Uma lista não pode ter o shape de 5x1 ou (5,1) -> Esse 1 tem que ser elimidado para ser somente (5,) é por isso, que usamos o meteodo squeeze()
array2 = np.arange(10)
s = array.reshape((array.shape[0],1))
print(s.size, 'elementos')
print(s.shape ,': tamanho anterior')
s = s.squeeze()
print(s)
print(s.shape ,': tamanho atual')

10 elementos
(10, 1) : tamanho anterior
[0 1 2 3 4 5 6 7 8 9]
(10,) : tamanho atual

# np.ravel()

In [116]:
# serve para pôr as listas em uma unica dimensão.
np.ravel(a_1)

array([1., 1., 1., 1., 1., 1., 1., 1.])

# Exercices

In [117]:
# Dados:

"""
def initiliasation(m,n):
    m: nombre de lignes
    n: nombre de colunnes
    retourne une matrice aliatoire(m, n+1)
    avec une colonne biais(remplie de "1") tout a droite.
    return
"""

'\ndef initiliasation(m,n):\n    m: nombre de lignes\n    n: nombre de colunnes\n    retourne une matrice aliatoire(m, n+1)\n    avec une colonne biais(remplie de "1") tout a droite.\n    return\n'

Em programação e ciência de dados, bias pode se referir a diferentes conceitos, dependendo do contexto. Vou explicar alguns dos mais comuns:

# 1. Bias em Machine Learning
Em machine learning, o bias (viés) é uma característica que descreve a tendência de um modelo em fazer suposições simplificadas sobre o que está aprendendo. Isso pode levar a previsões incorretas. O bias é uma parte do trade-off entre bias e variance, onde:

Alto bias significa que o modelo simplificou demais os dados, não conseguindo capturar as relações complexas (resultando em underfitting).
Baixo bias significa que o modelo está capturando bem a estrutura dos dados (mas, se for muito baixo, pode ocorrer overfitting, onde o modelo se ajusta demais aos dados de treinamento).
# 2. Bias em Estatística
No contexto estatístico, o bias refere-se à diferença entre a média das previsões do modelo e o valor real. Um modelo não enviesado (unbiased) é aquele cujas previsões, em média, estão corretas, mesmo que existam alguns erros.

# 3. Bias em Inteligência Artificial (IA) e Algoritmos
Bias também pode se referir a viés de dados ou viés algorítmico em IA, onde o modelo é tendencioso devido aos dados com que foi treinado. Por exemplo, se um conjunto de dados tiver representações desiguais de certas classes (como grupos sociais ou demográficos), o modelo pode se tornar injusto e produzir resultados que favorecem ou desfavorecem certos grupos.

# 4. Bias em Programação
Em programação em geral, bias também pode se referir a preferências implícitas no código ou algoritmos. Por exemplo, ao implementar uma função de ordenação ou tomada de decisões, certos parâmetros podem receber maior peso, influenciando o comportamento do programa de forma não intencional.

Exemplo em Machine Learning:
Um modelo de classificação que tenta prever se uma pessoa é aprovada para um empréstimo pode estar enviesado se foi treinado em um conjunto de dados onde apenas pessoas de um certo grupo demográfico receberam aprovação, levando o modelo a associar características como a etnia ou sexo com a aprovação de empréstimos.

Esse conceito é importante porque o bias pode comprometer a precisão e a justiça de sistemas e modelos.

# Données :

"""
def initiation(m,n):
    m : nombre de lignes
    n: nombre de colonnes
    retourner une matrice aliatoire(m, n+1)
    avec une colonne biais(remplie de "1") tout à droite.
    retour
"""

# Unindo dicionarios

In [119]:
d1 = {
    "Nome":['Jeovani Paxe', "Carlos"]
}

d2 = {
    "idade":[12, 20]
}

import pandas as pd
d1 = pd.DataFrame(d1)
d2 = pd.DataFrame(d2)

display(d1)
display(d2)

           Nome
0  Jeovani Paxe
1        Carlos

   idade
0     12
1     20

In [120]:
Data = np.concatenate((d1, d2), axis = 1)
d = pd.DataFrame(Data)
c = ["Nome", "Idade"]
d.columns = c
d

           Nome Idade
0  Jeovani Paxe    12
1        Carlos    20

In [121]:
d_lin = np.linspace(0, 10)
print(d_lin)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

In [122]:
d_lin.reshape(25,2)

array([[ 0.        ,  0.20408163],
       [ 0.40816327,  0.6122449 ],
       [ 0.81632653,  1.02040816],
       [ 1.2244898 ,  1.42857143],
       [ 1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796],
       [ 2.44897959,  2.65306122],
       [ 2.85714286,  3.06122449],
       [ 3.26530612,  3.46938776],
       [ 3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429],
       [ 4.48979592,  4.69387755],
       [ 4.89795918,  5.10204082],
       [ 5.30612245,  5.51020408],
       [ 5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061],
       [ 6.53061224,  6.73469388],
       [ 6.93877551,  7.14285714],
       [ 7.34693878,  7.55102041],
       [ 7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694],
       [ 8.57142857,  8.7755102 ],
       [ 8.97959184,  9.18367347],
       [ 9.3877551 ,  9.59183673],
       [ 9.79591837, 10.        ]])

In [123]:
ones = np.full((2,3),1)
zeros = np.full((2,3),0)

print(ones)
print()
print(zeros)

print('\nResultado: \n')
join_v = np.vstack((zeros, ones))
print(join_v)

[[1 1 1]
 [1 1 1]]

[[0 0 0]
 [0 0 0]]

Resultado:

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

In [124]:
res_v = np.concatenate((zeros, ones), axis = 0)
res_v

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [125]:
res_h = np.concatenate((zeros, ones), axis = 1)
res_h

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [131]:
res_h

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [135]:
np.delete(res_h,1, axis = 0)

array([[0, 0, 0, 1, 1, 1]])

In [140]:
np.delete(res_v, 2,axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])